/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CodeChat_Services_CONSTANTS_H
#define CodeChat_Services_CONSTANTS_H

#include "CodeChat_Services_types.h"



class CodeChat_ServicesConstants {
 public:
  CodeChat_ServicesConstants();

  int16_t THRIFT_PORT;
};

extern const CodeChat_ServicesConstants g_CodeChat_Services_constants;



#endif
