/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CodeChat_Services_constants.h"



const CodeChat_ServicesConstants g_CodeChat_Services_constants;

CodeChat_ServicesConstants::CodeChat_ServicesConstants() {
  THRIFT_PORT = 27376;

}



